apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: clo835
type: Opaque
data:
  # example: base64 encoded password
  MYSQL_ROOT_PASSWORD: cm9vdHBhc3N3b3Jk  # "rootpassword" in base64

