apiVersion: apps/v1
kind: Deployment
metadata:
  name: clo835-web
  namespace: clo835
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: 471112776853.dkr.ecr.us-east-1.amazonaws.com/clo835-web:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: ecr-registry

