apiVersion: v1
kind: Service
metadata:
  name: employees-nodeport
  namespace: clo835
spec:
  selector:
    app: web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30000
  type: NodePort

