apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
  namespace: mysql
  labels:
    app: employees
spec:
  containers:
  - name: mysql
    image: mysqlapp:v1
    imagePullPolicy: IfNotPresent
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: rootpass
    - name: MYSQL_DATABASE
      value: employees
    ports:
    - containerPort: 3306
