name: Build and Push to Amazon ECR

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AWS_REGION: us-east-1
  WEB_URI: 851725282833.dkr.ecr.us-east-1.amazonaws.com/clo835-webapp
  MYSQL_URI: 851725282833.dkr.ecr.us-east-1.amazonaws.com/clo835-mysql

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and Push WebApp image
        run: |
          echo "Building WebApp Docker image..."
          docker build -t webapp:latest -f Dockerfile .
          docker tag webapp:latest ${{ env.WEB_URI }}:latest
          docker push ${{ env.WEB_URI }}:latest

      - name: Build and Push MySQL image
        run: |
          echo "Building MySQL Docker image..."
          docker build -t mysql-custom:latest -f Dockerfile_mysql .
          docker tag mysql-custom:latest ${{ env.MYSQL_URI }}:latest
          docker push ${{ env.MYSQL_URI }}:latest
