name: Build Docker Images (Local Test)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout
        uses: actions/checkout@v4

      # 2️⃣ Build Web App Docker image locally
      - name: Build Web App image
        run: |
          echo "Building Web App image from Dockerfile..."
          docker build -t webapp:latest -f Dockerfile .

      # 3️⃣ Build MySQL Docker image locally
      - name: Build MySQL image
        run: |
          echo "Building MySQL image from Dockerfile_mysql..."
          docker build -t mysql-custom:latest -f Dockerfile_mysql .

      # 4️⃣ Verify Docker images
      - name: List Docker images
        run: docker images

