name: Build and Push to Amazon ECR

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main

env:
  AWS_REGION: us-east-1

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout the repository
      - name: Checkout
        uses: actions/checkout@v4

      # 2️⃣ Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          # Optional session token (only if using temporary creds like STS)
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ env.AWS_REGION }}

      # 3️⃣ Verify AWS identity
      - name: Verify AWS Authentication
        run: aws sts get-caller-identity

      # 4️⃣ Login to Amazon ECR
      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      # 5️⃣ Build and push the Web App image
      - name: Build & Push Web App
        run: |
          WEB_URI=${{ secrets.ECR_WEB_URI }}
          echo "Building and pushing webapp to $WEB_URI"
          docker build -t webapp:latest ./webapp
          docker tag webapp:latest ${WEB_URI}:latest
          docker push ${WEB_URI}:latest

      # 6️⃣ Pull, re-tag, and push the MySQL image
      - name: Pull, Tag & Push MySQL Image
        run: |
          MYSQL_URI=${{ secrets.ECR_MYSQL_URI }}
          echo "Pulling MySQL and pushing to $MYSQL_URI"
          docker pull mysql:8.0
          docker tag mysql:8.0 ${MYSQL_URI}:latest
          docker push ${MYSQL_URI}:latest
